// Simulation du RSA et de la prime d'activité (10 écrans relevés jusqu'au résultat), convertis en formulaires DSFR.
import { releve, esc, ind, lien, ext, page, ecrire, brief, conception, docComposant, SCRIPT_SIMU } from './lib.mjs';
import { convertir } from './convertir-etape.mjs';
const E = releve('simu-rsa-pa-app').etapes; const ECRAN = 'mds-simulation-rsa-pa';
const idx = (frag) => E.findIndex((e) => e.url.endsWith('/rsa-pa/' + frag));
const corps = (inner) => `        <div class="fr-container fr-mt-4v fr-mb-8v">\n            <div class="fr-grid-row fr-grid-row--gutters">\n                <div class="fr-col-12 fr-col-lg-8">\n${ind(inner, 20)}\n                </div>\n            </div>\n        </div>`;
const fil = (label) => [{ label: 'Simuler vos aides', href: lien('mds-simulateurs') }, { label: "RSA et Prime d'Activité", href: lien('mds-simulateur-rsa-pa') }, { label }];
const RETOUR = 'fr-btn fr-btn--secondary fr-icon-arrow-left-line fr-btn--icon-left', SUITE = 'fr-btn fr-icon-arrow-right-line fr-btn--icon-right';
const ETAPES = { Foyer: [1, 'Ressources'], Ressources: [2, 'Logement'], Logement: [3, 'Résultat'], Résultat: [4, null] };
// l'indicateur d'étapes maison du site devient celui du DSFR ; les prénoms d'essai sont retirés
const prep = (lignes, etape) => { const [n, suiv] = ETAPES[etape]; const indicateur = ['<fr-stepper>', `${etape} Étape ${n} sur 4`]; if (suiv) indicateur.push(`Étape suivante : ${suiv}`); let place = false;
  // ordre du site : bouton de retour éventuel, puis indicateur d'étapes
  const out = []; const premier = lignes.findIndex((l) => !['étape active', "Revenir à l'étape :"].includes(l));
  if (/^\[bouton "(Quitter la simulation|Précédent|Retour à l'étape .*)"\]/.test(lignes[premier] || '')) { out.push(lignes[premier]); lignes = lignes.filter((_, k) => k !== premier); }
  out.push(...indicateur);
  for (const l of lignes) { if (['Foyer', 'Ressources', 'Logement', 'Résultat', 'étape active', "Revenir à l'étape :", 'Test', 'Vous'].includes(l)) continue; if (/^La ressource ".*" a bien été ajoutée$/.test(l)) continue; if (/^\[bouton "(Ajouter un enfant|Ajouter une personne à charge)"\]/.test(l)) continue; if (/^\[lien "" ->/.test(l)) continue; if (!place && /^#+ /.test(l)) { out.push(l.replace(/^#+ /, '# ')); place = true; continue; } out.push(l); }
  // niveaux de titres sans saut (h1, puis au plus un niveau de plus que le précédent)
  let niveau = 0; return out.map((l) => { const m = l.match(/^(#+) (.*)$/); if (!m) return l; const n = Math.min(m[1].length, niveau + 1); niveau = n; return '#'.repeat(n) + ' ' + m[2]; }); };
const t = [];
const ecrireEtat = (fichier, frag, etape, opts) => { const e = E[idx(frag)]; const { html, dialogues, titre } = convertir(prep(e.lignesCompletes, etape), { cle: 'rsa', modales: e.modales, ...opts });
  ecrire(ECRAN, fichier, page({ titre: `${titre} - Simulation du RSA et de la prime d'activité`, fil: fil(titre), main: corps(html.replace(/\n?<!-- bouton non relié : [^>]* -->/g, '')), dialogues, script: SCRIPT_SIMU }).replace('<main role="main" id="content">', '<main role="main" id="content" data-simulation="rsa">'));
  t.push(`${titre} (${fichier})`); };
const QUITTER = { 'Quitter la simulation': [lien('mds-simulateur-rsa-pa'), RETOUR] };
ecrireEtat('index.html', 'foyer', 'Foyer', { suivant: 'etat-foyer.html', boutonsLiens: { ...QUITTER } });
ecrireEtat('etat-foyer.html', 'foyer_consultation', 'Foyer', { boutonsLiens: { ...QUITTER, Modifier: ['index.html', 'fr-btn fr-btn--secondary fr-icon-pencil-line fr-btn--icon-left'], Suivant: ['etat-ressources.html', SUITE] } });
ecrireEtat('etat-ressources.html', 'ressources_ouverture', 'Ressources', { boutonsLiens: { "Retour à l'étape Foyer": ['etat-foyer.html', RETOUR], 'Compléter les ressources': ['etat-ressources-situation.html', SUITE] } });
ecrireEtat('etat-ressources-situation.html', 'ressources_par_situation', 'Ressources', { suivant: 'etat-ressources-montants.html', boutonsLiens: { Précédent: ['etat-ressources.html', RETOUR] } });
ecrireEtat('etat-ressources-montants.html', 'ressources_saisie', 'Ressources', { suivant: 'etat-ressources-autres.html', boutonsLiens: { Précédent: ['etat-ressources-situation.html', RETOUR], 'Saisir ces montants plus tard': ['etat-ressources-autres.html', 'fr-btn fr-btn--tertiary'] } });
ecrireEtat('etat-ressources-autres.html', 'ressources_autre', 'Ressources', { suivant: 'etat-ressources-synthese.html', boutonsLiens: { Précédent: ['etat-ressources-montants.html', RETOUR] } });
ecrireEtat('etat-ressources-synthese.html', 'ressources_synthese', 'Ressources', { boutonsLiens: { "Retour à l'étape Foyer": ['etat-foyer.html', RETOUR], 'Ajouter une ressource': ['etat-ressources-autres.html', 'fr-btn fr-btn--secondary fr-icon-add-line fr-btn--icon-left'], Suivant: ['etat-logement.html', SUITE] } });
ecrireEtat('etat-logement.html', 'logement', 'Logement', { suivant: 'etat-logement-recap.html', boutonsLiens: { "Retour à l'étape Ressources": ['etat-ressources-synthese.html', RETOUR] } });
ecrireEtat('etat-logement-recap.html', 'logement_consultation', 'Logement', { boutonsLiens: { "Retour à l'étape Ressources": ['etat-ressources-synthese.html', RETOUR], Modifier: ['etat-logement.html', 'fr-btn fr-btn--secondary fr-icon-pencil-line fr-btn--icon-left'], 'Voir les résultats': ['etat-resultat.html', SUITE] } });
ecrireEtat('etat-resultat.html', 'resultat', 'Résultat', { liens: { 'Revenir à l’accueil': lien('mds-accueil') }, boutonsLiens: { 'Voir et modifier mes informations': ['etat-foyer.html', 'fr-btn fr-btn--secondary'] } });
// lien « Donnez-nous votre avis » : le site affiche une image cliquable sans texte
{ const f = `screens/${ECRAN}/etat-resultat.html`; const fs = await import('node:fs'); let h = fs.readFileSync(f, 'utf8'); h = h.replace(/<p>Aidez-nous à améliorer cette demarche Donnez-nous votre avis, cela ne prend que 2 minutes<\/p>/, `<p>Aidez-nous à améliorer cette demarche</p>\n                    <p>\n                        ${ext('https://jedonnemonavis.numerique.gouv.fr/Demarches/3785?&view-mode=formulaire-avis&nd_source=button&key=6dbcecd3e9b756af1f7b51dc028d3ad8', 'Donnez-nous votre avis, cela ne prend que 2 minutes')}\n                    </p>`); fs.writeFileSync(f, h); }
ecrire(ECRAN, 'brief.md', brief({ titre: "Simulation du RSA et de la prime d'activité, traduite en DSFR", source: 'https://www.mesdroitssociaux.gouv.fr/vos-simulateurs/#/rsa-pa/foyer (parcouru jusqu\'au résultat avec une situation d\'essai : personne seule salariée avec plusieurs ressources, locataire à Paris ; aucune demande déposée)', story: "En tant qu'usager, je veux décrire mon foyer, mes ressources et mon logement, afin d'estimer mes droits au RSA et à la prime d'activité.", depart: 'Démarche à étapes (Foyer, Ressources, Logement, Résultat) ; la page de prérequis mds-simulateur-rsa-pa sert d\'introduction. Écrans produits par scripts/mds/build-rsa.mjs (convertisseur scripts/mds/convertir-etape.mjs).', contenus: `Écrans repris du site : ${t.join(' ; ')}. Les montants sont demandés en net fiscal avant prélèvement à la source, mois par mois sur quatre mois. Résultat relevé : « Simulation terminée ! », « D’après les informations que vous avez communiquées, vous n’êtes éligible à aucune des aides. », renvoi vers la CAF ou la MSA, lien vers « Je donne mon avis ».`, etats: 'Un état par écran ; les boutons enchaînent les écrans et contrôlent les champs obligatoires ; le récapitulatif du foyer, la synthèse des ressources, le récapitulatif du logement et le résultat montrent la situation d\'essai.' }));
ecrire(ECRAN, 'conception.md', conception({ titre: "Simulation du RSA et de la prime d'activité", intro: 'Démarche à étapes, un état par écran du site.', composants: [docComposant('stepper', "Indicateur d'étapes", 'l\'indicateur maison du site (liste d\'étapes) devient l\'indicateur DSFR à quatre étapes.'), docComposant('form', 'Formulaire', 'un formulaire par écran de saisie, contrôle à l\'envoi.'), '- Doc lue : reference/doc/modeles/date-unique.md — date de naissance en trois champs.', docComposant('radio', 'Bouton radio', 'sexe, situation matrimoniale, régime d\'Alsace-Moselle, statut de logement.'), docComposant('checkbox', 'Case à cocher', 'situations professionnelle, scolaire, personnelle et ressources reçues ; précisions en texte d\'aide sous chaque choix. Les catégories « Allocations » dépassent cinq choix, nombre au-delà duquel la doc conseille une liste déroulante : gardées en cases car le choix est multiple.'), docComposant('input', 'Champ de saisie', 'prénom, montants mensuels, code postal ou ville, loyer.')].join('\n'), note: "**Retenus** : écrans, questions et textes du site, indicateur d'étapes DSFR. **Écartés** : boutons « Ajouter un enfant » et « Ajouter une personne à charge » (formulaires non relevés) ; prénom d'essai « Test » affiché par le site ; message « La ressource … a bien été ajoutée » ; recherche de commune avec suggestions (champ texte simple). **Écarts assumés** : un seul écran de saisie de montants représente les écrans répétés par ressource ; synthèses et résultat figés sur la situation d'essai, dont le résultat non éligible. **Questions ouvertes** : relever les formulaires enfant et personne à charge ; relever un résultat éligible avec montants." }));
console.log('RSA écrit :\n' + t.join('\n'));
